// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: junk.proto

package junk

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EmptyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMsg) Reset() {
	*x = EmptyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_junk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMsg) ProtoMessage() {}

func (x *EmptyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_junk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMsg.ProtoReflect.Descriptor instead.
func (*EmptyMsg) Descriptor() ([]byte, []int) {
	return file_junk_proto_rawDescGZIP(), []int{0}
}

type JunkMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Junk string `protobuf:"bytes,1,opt,name=junk,proto3" json:"junk,omitempty"`
}

func (x *JunkMsg) Reset() {
	*x = JunkMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_junk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JunkMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JunkMsg) ProtoMessage() {}

func (x *JunkMsg) ProtoReflect() protoreflect.Message {
	mi := &file_junk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JunkMsg.ProtoReflect.Descriptor instead.
func (*JunkMsg) Descriptor() ([]byte, []int) {
	return file_junk_proto_rawDescGZIP(), []int{1}
}

func (x *JunkMsg) GetJunk() string {
	if x != nil {
		return x.Junk
	}
	return ""
}

var File_junk_proto protoreflect.FileDescriptor

var file_junk_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6a, 0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6a, 0x75,
	0x6e, 0x6b, 0x22, 0x0a, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x22, 0x1d,
	0x0a, 0x07, 0x4a, 0x75, 0x6e, 0x6b, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x75, 0x6e,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6a, 0x75, 0x6e, 0x6b, 0x32, 0x35, 0x0a,
	0x04, 0x4a, 0x75, 0x6e, 0x6b, 0x12, 0x2d, 0x0a, 0x08, 0x54, 0x61, 0x6b, 0x65, 0x4a, 0x75, 0x6e,
	0x6b, 0x12, 0x0d, 0x2e, 0x6a, 0x75, 0x6e, 0x6b, 0x2e, 0x4a, 0x75, 0x6e, 0x6b, 0x4d, 0x73, 0x67,
	0x1a, 0x0e, 0x2e, 0x6a, 0x75, 0x6e, 0x6b, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x73, 0x67,
	0x22, 0x00, 0x28, 0x01, 0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x3b, 0x6a,
	0x75, 0x6e, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_junk_proto_rawDescOnce sync.Once
	file_junk_proto_rawDescData = file_junk_proto_rawDesc
)

func file_junk_proto_rawDescGZIP() []byte {
	file_junk_proto_rawDescOnce.Do(func() {
		file_junk_proto_rawDescData = protoimpl.X.CompressGZIP(file_junk_proto_rawDescData)
	})
	return file_junk_proto_rawDescData
}

var file_junk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_junk_proto_goTypes = []interface{}{
	(*EmptyMsg)(nil), // 0: junk.EmptyMsg
	(*JunkMsg)(nil),  // 1: junk.JunkMsg
}
var file_junk_proto_depIdxs = []int32{
	1, // 0: junk.Junk.TakeJunk:input_type -> junk.JunkMsg
	0, // 1: junk.Junk.TakeJunk:output_type -> junk.EmptyMsg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_junk_proto_init() }
func file_junk_proto_init() {
	if File_junk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_junk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_junk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JunkMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_junk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_junk_proto_goTypes,
		DependencyIndexes: file_junk_proto_depIdxs,
		MessageInfos:      file_junk_proto_msgTypes,
	}.Build()
	File_junk_proto = out.File
	file_junk_proto_rawDesc = nil
	file_junk_proto_goTypes = nil
	file_junk_proto_depIdxs = nil
}
