// Code generated by protoc-gen-go. DO NOT EDIT.
// source: junk.proto

package junk

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyMsg struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyMsg) Reset()         { *m = EmptyMsg{} }
func (m *EmptyMsg) String() string { return proto.CompactTextString(m) }
func (*EmptyMsg) ProtoMessage()    {}
func (*EmptyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_junk_946f17fc8169be39, []int{0}
}
func (m *EmptyMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyMsg.Unmarshal(m, b)
}
func (m *EmptyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyMsg.Marshal(b, m, deterministic)
}
func (dst *EmptyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyMsg.Merge(dst, src)
}
func (m *EmptyMsg) XXX_Size() int {
	return xxx_messageInfo_EmptyMsg.Size(m)
}
func (m *EmptyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyMsg proto.InternalMessageInfo

type JunkMsg struct {
	Junk                 string   `protobuf:"bytes,1,opt,name=junk,proto3" json:"junk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JunkMsg) Reset()         { *m = JunkMsg{} }
func (m *JunkMsg) String() string { return proto.CompactTextString(m) }
func (*JunkMsg) ProtoMessage()    {}
func (*JunkMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_junk_946f17fc8169be39, []int{1}
}
func (m *JunkMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JunkMsg.Unmarshal(m, b)
}
func (m *JunkMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JunkMsg.Marshal(b, m, deterministic)
}
func (dst *JunkMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JunkMsg.Merge(dst, src)
}
func (m *JunkMsg) XXX_Size() int {
	return xxx_messageInfo_JunkMsg.Size(m)
}
func (m *JunkMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_JunkMsg.DiscardUnknown(m)
}

var xxx_messageInfo_JunkMsg proto.InternalMessageInfo

func (m *JunkMsg) GetJunk() string {
	if m != nil {
		return m.Junk
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyMsg)(nil), "junk.EmptyMsg")
	proto.RegisterType((*JunkMsg)(nil), "junk.JunkMsg")
}

func init() { proto.RegisterFile("junk.proto", fileDescriptor_junk_946f17fc8169be39) }

var fileDescriptor_junk_946f17fc8169be39 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2a, 0xcd, 0xcb,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xb8, 0xb8, 0x38, 0x5c, 0x73,
	0x0b, 0x4a, 0x2a, 0x7d, 0x8b, 0xd3, 0x95, 0x64, 0xb9, 0xd8, 0xbd, 0x4a, 0xf3, 0xb2, 0x7d, 0x8b,
	0xd3, 0x85, 0x84, 0xb8, 0xc0, 0xd2, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x91,
	0x29, 0x17, 0x0b, 0x48, 0x5a, 0x48, 0x97, 0x8b, 0x23, 0x24, 0x31, 0x3b, 0x15, 0xcc, 0xe6, 0xd5,
	0x03, 0x9b, 0x08, 0xd5, 0x26, 0xc5, 0x07, 0xe1, 0xc2, 0x4d, 0x64, 0xd0, 0x60, 0x74, 0xe2, 0x88,
	0x62, 0xd3, 0xb3, 0x06, 0x09, 0x27, 0xb1, 0x81, 0x2d, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x7c, 0xe4, 0xff, 0xf7, 0x86, 0x00, 0x00, 0x00,
}
